language: node_js
node_js: "6"
script:
      - ./node_modules/.bin/webpack --output-path build
      - sudo python -H -m pip install s3cmd
      - s3cmd sync --delete-removed -P -M -r build/ s3://marache.net-static/projects/gravity
notifications:
    email:
        on_failure: always

